'use strict';

const { ActionRowBuilder, AttachmentBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, StringSelectMenuBuilder } = require('discord.js');
const { EVENT_KEYS, EVENT_LABELS } = require('../../app/constants');
const { readEventData } = require('../events/event-repository');
const { readStore } = require('./repository');
const { selectTeam, formatRating } = require('./selection');
const { renderTeamOfTournament } = require('./renderer');
const { deleteTemporary, publishTeamOfTournament, tournamentId, canPublish } = require('./publication');
const { normalizePosition } = require('./position-normalizer');

function buildTottAdminMenu() { return { content: 'Team of the Tournament – Test und Verwaltung', components: [new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('admin_tott_action_select').setPlaceholder('Aktion auswaehlen').addOptions([
  { label: 'Renderer mit Mock-Daten testen', value: 'mock' }, { label: 'Abgeschlossenes Turnier als Vorschau', value: 'preview' }, { label: 'Auswahlberechnung anzeigen', value: 'selection' }, { label: 'EA-Verknuepfung eines Teams testen', value: 'ea_test' }, { label: 'Statistikjob-Status anzeigen', value: 'jobs' }, { label: 'Manuelle Veroeffentlichung vorbereiten', value: 'manual' },
]))] }; }
function completedEventOptions() { return EVENT_KEYS.map(eventKey => { const event = readEventData(eventKey); const id = tournamentId(eventKey, event); const cup = event?.cycle?.cupNumber || String(event?.cycle?.cycleKey || '').match(/\d+/)?.[0] || '-'; return { label: `${EVENT_LABELS[eventKey] || eventKey} | Cup ${cup}`, description: `${event?.ceremony?.postedAt || event?.ceremony?.readyAt || 'kein Abschlusszeitpunkt'}`.slice(0, 100), value: eventKey }; }).filter(option => readEventData(option.value)?.ceremony?.status === 'posted'); }
function buildCompletedEventSelect(customId) { const options = completedEventOptions(); if (!options.length) throw new Error('Kein abgeschlossenes Turnier gefunden.'); return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(customId).setPlaceholder('Abgeschlossenes Turnier auswaehlen').addOptions(options)); }
function mockSelection() { const groups = ['goalkeeper', ...Array(3).fill('defender'), ...Array(5).fill('midfielder'), ...Array(2).fill('forward')]; const names = ['Torwart Test', 'IV Kurz', 'SehrLangerDefenderNameTest', 'Defender Drei', 'Mittelfeld Eins', 'Zehner Mit Langem Namen', 'Sechser Zwei', 'Linke Seite', 'Rechte Seite', 'Stuermer Eins', 'Stuermer Zwei']; const players = groups.flatMap((group, index) => [1,2].map(game => ({ isHuman: true, playerId: `mock-${index}`, playerName: names[index], proClubId: 'mock', discordTeamId: 'mock', normalizedPosition: normalizePosition(group), rating: 7.4 + index / 10 + game / 100, goals: index % 3, assists: index % 2, playerOfTheMatch: index % 4 === 0, secondsPlayed: 900 }))); return selectTeam([{ tournamentId: 'mock', phase: 'groups', players }]); }
async function sendRenderToTestChannel({ guild, testChannelId, selection, label }) { let filePath; try { filePath = await renderTeamOfTournament({ slots: selection.slots }); const channel = await guild.channels.fetch(testChannelId); if (!channel?.isTextBased()) throw new Error('Konfigurierter Admin-Testkanal ist nicht textbasiert.'); const message = await channel.send({ content: `**TEST – ${label} – keine Live-Veröffentlichung**`, files: [new AttachmentBuilder(filePath)] }); return { messageId: message.id, channelId: channel.id }; } finally { deleteTemporary(filePath); } }
function stateFor(eventKey) { const event = readEventData(eventKey); const id = tournamentId(eventKey, event); const store = readStore(); return { event, id, jobs: store.jobs.filter(job => job.tournamentId === id), matches: store.matches.filter(match => match.tournamentId === id), publication: store.publications.find(item => item.tournamentId === id) }; }
function jobSummaryEmbed(eventKey) { const state = stateFor(eventKey); const count = status => state.jobs.filter(job => status.includes(job.status)).length; const details = state.jobs.slice(0, 15).map(job => `${job.tournamentMatchId}: ${job.home.discordTeamId} vs ${job.away.discordTeamId} | ${job.result.homeGoals}:${job.result.awayGoals} | ${job.status} | Versuch ${job.attempts}${job.nextAttemptAt ? ` | naechster ${job.nextAttemptAt}` : ''}${job.foundEaMatchId ? ` | EA ${job.foundEaMatchId}` : ''}${job.errorReason ? ` | ${job.errorReason}` : ''}`).join('\n') || 'Keine Jobs'; const publication = state.publication ? `${state.publication.status} | Start: ${state.publication.postingStartedAt || '-'} | Message-ID: ${state.publication.messageId || 'nicht gespeichert'}` : 'nicht gestartet'; return new EmbedBuilder().setTitle(`TOTT Jobstatus – ${EVENT_LABELS[eventKey] || eventKey}`).setDescription(details.slice(0,4096)).addFields({ name: 'Zusammenfassung', value: `Gesamt: ${state.jobs.length}\nErfolgreich: ${count(['found','manually_assigned'])}\nOffen/Retry: ${count(['pending','processing'])}\nUnresolved: ${count(['ambiguous','not_found'])}\nFailed: ${count(['failed'])}\nSkipped: ${count(['skipped_unverified_team'])}\nDuplicate: ${count(['duplicate_match'])}` }, { name: 'Publishing / Recovery', value: publication.slice(0,1024) }); }
function selectionEmbed(eventKey) { const state = stateFor(eventKey); const selection = selectTeam(state.matches); const lines = Object.entries(selection.slots).map(([slot, player]) => player ? `${slot}: ${player.playerName} | ${formatRating(player.average)} | ${player.matches} Spiele | ${player.goals} Tore | ${player.assists} Vorlagen | ${player.potm} MoM | ${player.primaryGroup}${selection.fallbacks.includes(player.primaryGroup) ? ' | 1-Spiel-Fallback' : ''}` : `${slot}: Keine Wertung`); return new EmbedBuilder().setTitle(`TOTT Auswahl – ${EVENT_LABELS[eventKey] || eventKey}`).setDescription(lines.join('\n')); }
function manualConfirmPayload(eventKey) { const state = stateFor(eventKey); const eligibility = canPublish(eventKey, state.event); return { content: `Manuelle Veroeffentlichung fuer **${EVENT_LABELS[eventKey] || eventKey}**\nStatus: ${eligibility.ok ? 'bereit' : eligibility.reason}\nJobs: ${state.jobs.length}, Matches: ${state.matches.length}`, components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`admin_tott_publish_confirm:${eventKey}`).setLabel('Jetzt produktiv veroeffentlichen').setStyle(ButtonStyle.Danger).setDisabled(!eligibility.ok))] }; }
module.exports = { buildCompletedEventSelect, buildTottAdminMenu, jobSummaryEmbed, manualConfirmPayload, mockSelection, publishTeamOfTournament, selectionEmbed, sendRenderToTestChannel, stateFor };
