'use strict';

const fs = require('fs');
const { AttachmentBuilder } = require('discord.js');
const config = require('./config');
const { readStore, updateStore } = require('./repository');
const { selectTeam } = require('./selection');
const { renderTeamOfTournament } = require('./renderer');

const TERMINAL = new Set(['found', 'ambiguous', 'not_found', 'duplicate_match', 'skipped_unverified_team', 'failed', 'manually_assigned', 'completed_without_stats']);
const POSTING_STALE_MS = 15 * 60 * 1000;
function tournamentId(eventKey, event) { return `${eventKey}:${event?.cycle?.cycleKey || event?.cycle?.eventDate || 'unknown'}`; }
function cupNumber(event) { return event?.cycle?.cupNumber || String(event?.cycle?.cycleKey || '').match(/\d+/)?.[0] || null; }
function publicationState(eventKey, event) { const id = tournamentId(eventKey, event); const store = readStore(); return { id, store, publication: store.publications.find(item => item.tournamentId === id) || null, jobs: store.jobs.filter(job => job.tournamentId === id), matches: store.matches.filter(match => match.tournamentId === id) }; }
function canPublish(eventKey, event) { const state = publicationState(eventKey, event); if (event?.ceremony?.status !== 'posted') return { ok: false, reason: 'ceremony_not_posted', ...state }; if (state.publication?.status === 'posted' || state.publication?.messageId) return { ok: false, reason: 'already_posted', ...state }; if (state.publication?.status === 'posting') { const age = Date.now() - new Date(state.publication.postingStartedAt || state.publication.createdAt || 0).getTime(); return { ok: false, reason: age >= POSTING_STALE_MS ? 'stale_posting_requires_admin_investigation' : 'publishing_in_progress', ...state }; } if (state.jobs.some(job => !TERMINAL.has(job.status))) return { ok: false, reason: 'jobs_open', ...state }; if (!state.matches.length) return { ok: false, reason: 'no_statistics', ...state }; return { ok: true, ...state }; }
function deleteTemporary(filePath) { if (!filePath) return; try { fs.unlinkSync(filePath); console.log(`[tott] Temporaere Datei geloescht: ${filePath}`); } catch (error) { if (error.code !== 'ENOENT') console.warn(`[tott] Temporaere Datei konnte nicht geloescht werden: ${error.message}`); } }
function cleanupOldRenders(maxAgeMs = 24 * 60 * 60 * 1000) { const { DIR } = require('./repository'); if (!fs.existsSync(DIR)) return 0; let removed = 0; for (const name of fs.readdirSync(DIR)) { if (!/^render-.*\.png$/i.test(name)) continue; const file = require('path').join(DIR, name); if (Date.now() - fs.statSync(file).mtimeMs < maxAgeMs) continue; deleteTemporary(file); removed += 1; } return removed; }
async function publishTeamOfTournament({ guild, eventKey, event, test = false, channelId = null }) { const state = canPublish(eventKey, event); if (!test && !state.ok) return { posted: false, reason: state.reason }; const selection = selectTeam(state.matches); if (!Object.values(selection.slots).some(Boolean)) return { posted: false, reason: 'no_players' }; if (!test) { let reserved = false; updateStore(store => { if (store.publications.some(item => item.tournamentId === state.id && ['posting','posted'].includes(item.status))) return store; const timestamp = new Date().toISOString(); store.publications.push({ tournamentId: state.id, cupNumber: cupNumber(event), status: 'posting', renderStatus: 'pending', postingStartedAt: timestamp, createdAt: timestamp }); reserved = true; return store; }); if (!reserved) return { posted: false, reason: 'already_posted' }; }
  let renderPath; try { renderPath = await renderTeamOfTournament({ slots: selection.slots }); const channel = await guild.channels.fetch(channelId || config.channelId); if (!channel?.isTextBased()) throw new Error('TOTT-Kanal ist nicht textbasiert.'); const number = cupNumber(event); const message = await channel.send({ content: `${test ? '**TEST – keine Live-Veröffentlichung**\n' : ''}# Loco Night Cup${number ? ` #${number}` : ''} – Team of the Tournament\nDie besten Spieler des Turniers auf Basis der EA-Spielbewertungen.`, files: [new AttachmentBuilder(renderPath)] }); if (!test) updateStore(store => { const item = store.publications.find(entry => entry.tournamentId === state.id); Object.assign(item, { status: 'posted', renderStatus: 'completed', publishedAt: new Date().toISOString(), channelId: channel.id, messageId: message.id, selectedPlayers: selection.slots, usedEaMatchIds: state.matches.map(match => match.eaMatchId) }); return store; }); console.log(`[tott] Discord-Post erfolgreich: ${state.id}${test ? ' (Test)' : ''}`); return { posted: true, messageId: message.id, selection }; } catch (error) { if (!test) updateStore(store => { const item = store.publications.find(entry => entry.tournamentId === state.id); if (item) Object.assign(item, { status: 'failed', renderStatus: 'failed', error: error.message }); return store; }); throw error; } finally { deleteTemporary(renderPath); } }
async function maybePublishAfterCeremony({ guild, eventKey, event }) { return publishTeamOfTournament({ guild, eventKey, event }); }
module.exports = { POSTING_STALE_MS, TERMINAL, canPublish, cleanupOldRenders, cupNumber, deleteTemporary, maybePublishAfterCeremony, publishTeamOfTournament, tournamentId };
